"C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\python.exe" "C:/Users/Lea Geibel/Documents/ETH/MASTERTHESIS/snowicesat/sandbox/Vierzack_copy/setup_gdirs_lea_cp.py"
2019-02-20 16:02:24: oggm.cfg: Using configuration file: c:\users\lea geibel\documents\eth\masterthesis\snowicesat\sandbox\vierzack_copy\oggm\oggm\params.cfg
2019-02-20 16:02:24: crampon.cfg: Parameter file: C:\Users\Lea Geibel\Documents\ETH\MASTERTHESIS\snowicesat\sandbox\Vierzack_copy\CH_params.cfg
Delete all glacier directories? [Y/n] 2019-02-20 16:02:24: __main__: Number of glaciers: 7
Y
2019-02-20 16:02:35: oggm.workflow: Execute Entity task define_glacier_region_crampon on 7 glaciers
GlacierDirectory is created, now calling execute_entity_task(gis.define_glacier_region, new_gdirs)
2019-02-20 16:02:38: oggm.cfg: Using configuration file: c:\users\lea geibel\documents\eth\masterthesis\snowicesat\sandbox\vierzack_copy\oggm\oggm\params.cfg
2019-02-20 16:02:38: crampon.cfg: Parameter file: C:\Users\Lea Geibel\Documents\ETH\MASTERTHESIS\snowicesat\sandbox\Vierzack_copy\CH_params.cfg
2019-02-20 16:02:39: __mp_main__: Number of glaciers: 7
Delete all glacier directories? [Y/n] Y
GlacierDirectory is created, now calling execute_entity_task(gis.define_glacier_region, new_gdirs)
2019-02-20 16:04:30: oggm.workflow: Execute Entity task define_glacier_region_crampon on 7 glaciers
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lea Geibel\Documents\ETH\MASTERTHESIS\snowicesat\sandbox\Vierzack_copy\setup_gdirs_lea_cp.py", line 43, in <module>
    gdirs = workflow.init_glacier_regions(rgidf, reset=True, force=False)
  File "c:\users\lea geibel\documents\eth\masterthesis\snowicesat\sandbox\vierzack_copy\crampon\crampon\workflow.py", line 80, in init_glacier_regions_crampon
    execute_entity_task(gis.define_glacier_region, new_gdirs)
  File "c:\users\lea geibel\documents\eth\masterthesis\snowicesat\sandbox\vierzack_copy\oggm\oggm\workflow.py", line 146, in execute_entity_task
    mppool = init_mp_pool(cfg.CONFIG_MODIFIED)
  File "c:\users\lea geibel\documents\eth\masterthesis\snowicesat\sandbox\vierzack_copy\oggm\oggm\workflow.py", line 46, in init_mp_pool
    global_lock = mp.Manager().Lock()
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\context.py", line 55, in Manager
    m.start()
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\managers.py", line 479, in start
    self._process.start()
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Lea Geibel\Anaconda3\envs\snowicesat\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.